config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {omniauth_callbacks: "callbacks"}

  root "static_pages#home"
  get "static_pages/help"
  resources :users
  resources :posts, only: [:index, :show]
  resources :teams
  resources :players
  resources :comments
  resources :bets, only: [:edit, :update]
  
  resources :matches do 
    resources :bets, except: [:destroy, :show, :index]
  end

  namespace :admin do
    root "seasons#show"
    resources :seasons
    resources :matches
    resources :players
    resources :teams
    resources :posts
    resources :users
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  before_action :load_seasons, only: :home

  def home
    @posts = Post.order_by_date
  end

  def help
  end

  private
  def load_seasons
    @seasons = Season.all
  end
end

app/views/static_pages/_bottom_footer.html.erb
<div id="frg-footer">
  <div class="container">
    <div class="row">
      <div class="frg-bottom-menu">
        <ul class="nav navbar nav-pills">
          <li><%= link_to t("static_pages.home") %></li>
          <li><%= link_to t("static_pages.help") %></li>
          <li><%= link_to t("home.contact") %></li>
          <li><%= link_to t("home.site_map") %></li>
          <li><%= link_to t("home.on_pitch") %></li>
        </ul>
      </div>
      <div class="frg-bottom-info">
        <h4><%= t "static_pages.title" %></h4>
      </div>
    </div>
  </div>
</div>

app/views/static_pages/_left_content_ranking.html.erb
<div class="col-sm-4">
  <div class="frg-result-rank">
    <div class="frg-tabs">
      <ul>
        <li><%= link_to t"home.result" %></li>
        <li><%= link_to t"home.ranking" %></li>
      </ul>
      <div id="frg-rank">
        <table class="table table-hover table-bordered">
          <thead>
            <tr>
              <th colspan="2">
                <%= select_tag "season_id", options_for_select(@seasons
                  .collect {|season| [season.name, season.id]}),
                  {class: "form-control"} %>
              </th>
            </tr>
          </thead>
          <tbody>
            <% @seasons.each do |season| %>
              <% season.load_season_team.each do |season_team| %>
                <tr>
                  <td><%= season_team.rank %></td>
                  <td><%= season_team.team_name %></td>
                </tr>
              <% end %>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

app/views/static_pages/_post.html.erb
<div id="frg-featured">
  <div class="row">
    <div class="col-sm-8">
      <div class="frg-slider">
        <div class="thumbnail">
          <a href="#"><img src="https://placehold.it/601x360"></a>
          <div class="caption">
            <h4><%= link_to t "home.banner_title" %></h4>
            <p class="frg-tag"><span><%= link_to t "home.real_madrid" %></span>
              <span><%= link_to t "home.aletico" %></span></p>
            <p class="frg-summary"><%= t "static_pages.title" %>
              <%= t "home.banner_news" %></p>
          </div>
        </div>
      </div>
    </div>
  <div class="col-sm-4">
    <div class="panel panel-success">
      <div class="panel-heading">
        <h3 class="panel-title"><%= t "home.newest_news" %></h3>
      </div>
      <div class="panel-body">
        <ul>
          <% @posts.each do |post| %>
            <li><%= link_to post.title, post_path(post),
              class: "fa fa-caret-right" %>
            </li>
            <br>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
</div>

app/views/static_pages/_top_header.html.erb
<div id="frg-header">
  <div id="frg-top">
    <div class="frg-top">
      <div class="container">
          <div class="row">
            <ul class="nav nav-pills pull-left">
              <li><%= link_to t("home.schedule") ,"#" %></li>
              <li><%= link_to t("home.germany") ,"#" %></li>
              <li><%= link_to t("home.france") ,"#" %></li>
              <li><%= link_to t("home.live_score") ,"#" %></li>
            </ul>
          <p class="pull-right"><%= t "home.ffn" %></p>
        </div>
      </div>
    </div>
  </div>
  <div id="frg-banner">
    <div class="frg-banner">
      <div class="container">
        <div class="row">
          <div class="pull-left">
            <%= image_tag("logo-ffn-2.png", size: "100") %>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div id="frg-menu">
    <div class="frg-menu">
      <div class="container">
        <div class="row">
          <ul class="nav navbar nav-pills">
            <li><i class="fa fa-home fa-lg"></i></li>
            <li><%= link_to t("home.hot_news") %></li>
            <li><%= link_to t("home.world_cup") %></li>
            <li><%= link_to t("home.euro") %></li>
            <li><%= link_to t("home.copa_american"), class: "fa fa-caret-down" %>
              <ul>
                <li><%= link_to t("home.brazil") %></li>
                <li><%= link_to t("home.argentina") %></li>
              </ul>
            </li>
            <li><%= link_to t("home.transfer") %></li>
            <li><%= link_to t("home.england"), class: "fa fa-caret-down" %></a>
              <ul>
                <li><%= link_to t("home.mu") %></li>
                <li><%= link_to t("home.chel") %></li>
              </ul>
            </li>
            <li><%= link_to t("home.vietnam") %></li>
            <li><%= link_to t("home.spain"), "#" %>
            </li>
            <li><%= link_to t("home.video") %></li>
            <li class="pull-right"><%= link_to t("home.on_pitch") %></li>
          </ul>
        </div>
      </div>
    </div>
  </div>
  <div id="frg-headline">
    <div class="frg-headline">
      <div class="container">
        <div class="row">
          <div class="col-sm-8">
            <div class="frg-small-title">
              <span><%= t "home.hot" %></span>
              <div>
              <marquee behavior="scroll" scrollamount="2" direction="left" width="580">
                <ul class="list-inline">
                  <li><%= link_to t("home.germany"), class: "fa fa-circle" %></li>
                  <li><%= link_to t("home.france"), class: "fa fa-circle" %></li>
                  <li><%= link_to t("home.spain"), class: "fa fa-circle" %></li>
                  <li><%= link_to t("home.vietnam"), class: "fa fa-circle" %></li>
                  <li><%= link_to t("home.england"), class: "fa fa-circle" %></li>
                </ul>
              </marquee>
              </div>
            </div>
          </div>
          <div class="col-sm-4">
            <form class="form-horizontal">
              <div class="input-group">
                <input type="search" class="form-control" name="search"
                  placeholder="<%= t("home.search") %>" id="frg-search">
                <span class="input-group-btn">
                  <button class="btn btn-default btn-info" type="submit">
                    <i class="fa fa-search"></i>
                  </button>
                </span>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/static_pages/home.html.erb
<% provide :title, t("static_pages.home") %>
<div class="row">
  <body>
    <%= render "top_header" %>
    <%= render "post" %>
    <div id="frg-wrapper">
      <div class="container">
        <div id="frg-schedule">
          <div class="row">
            <div class="col-sm-8">
              <div class="frg-schedule">
                <h1><i class="fa fa-soccer-ball-o"></i><%= t "home.schedule" %></h1>
                <div class="frg-schedule-daily">
                  <% @seasons.each do |season| %>
                    <h2><%= season.name %></h2>
                    <table class="table table-hover table-bordered">
                      <thead>
                        <tr>
                          <th><%= t "home.start" %></th>
                          <th><%= t "home.match" %></th>
                          <th><%= t "home.goal" %></th>
                          <th><%= t "home.point" %></th>
                        </tr>
                      </thead>
                      <tbody>
                      <% season.load_matches.each do |hash_match| %>
                        <tr>
                          <td colspan="5">
                            <strong class="text-info"><%= hash_match.first %></strong>
                          </td>
                        </tr>
                        <% hash_match.second.each do |match| %>
                          <tr>
                            <td><i class="fa fa-tv"></i><%= match.hour %></td>
                            <% if match.exist_bet? current_user %>
                              <td class="td_style">
                                <%= link_to match.name, edit_bet_path(match.load_bet(current_user)) %>
                              </td>
                            <% else %>
                              <td class="td_style"><%= link_to match.name, new_match_bet_path(match) %></td>
                            <% end %>
                            <td>
                              <%= match.goals %>
                            </td>
                            <td>
                              <%= match.points %>
                            </td>
                          </tr>
                        <% end %>
                      <% end %>
                      </tbody>
                    </table>
                  <% end %>
                </div>
                <p><%= link_to t("home.more_football"), class: "fa fa-caret-right" %></p>
              </div>
            </div>
            <%= render "left_content_ranking" %>
          </div>
        </div>
      </div>
    </div>
    <%= render "bottom_footer" %>
  </body>
</div>