config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {omniauth_callbacks: "callbacks"}

  root "static_pages#home"
  get "static_pages/help"
  resources :users
  resources :posts, only: [:index, :show]
  resources :teams
  resources :players
  resources :comments
  resources :bets, only: [:edit, :update]
  
  resources :matches do 
    resources :bets, except: [:destroy, :show, :index]
  end

  namespace :admin do
    root "seasons#show"
    resources :seasons
    resources :matches
    resources :players
    resources :teams
    resources :posts
    resources :users
  end
end

app/models/player.rb
class Player < ActiveRecord::Base
  belongs_to :team

  validates :name, presence: true, length: {maximum: 50}
  validates :position, presence: true, length: {maximum: 20}
  validates :nationality, presence: true, length: {maximum: 20}
  validates :jersey_number, presence: true,
    numericality: {only_integer: true, greater_than: 0}

  mount_uploader :image, LogoUploader
end

app/controllers/admin/players_controller.rb
class Admin::PlayersController < ApplicationController
  load_and_authorize_resource
  before_action :load_teams, only: [:new, :edit]

  def index
    @q = Player.search params[:q]
    @players = @q.result distinct: true
  end

  def new
  end

  def edit
  end

  def show
    @seasons = Season.all
  end

  def create
    if @player.save
      flash.now[:success] = t "admin.player.create_success"
      redirect_to admin_players_path
    else
      load_teams
      flash.now[:warning] = t "admin.player.wrong" 
      render :new
    end
  end

  def update
    if @player.update_attributes player_params
      flash[:success] = t "admin.player.update_player_success"
      respond_to do |format|
        format.html {redirect_to :back}
        format.js
      end
    else
      flash[:danger] = t "admin.player.update_player_error"
      render :edit
    end
  end

  def destroy
    @player.destroy
    flash[:success] = t "admin.player.delete_player_success"
    redirect_to admin_players_path
  end

  private
  def player_params
    params.require(:player).permit :name, :date_of_birth, :position,
      :jersey_number, :nationality, :image, :team_id
  end

  def load_teams
    @teams = Team.all
  end
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  load_and_authorize_resource

  def show
    @seasons = Season.all
  end
end

app/views/admin/players/_form.html.erb
<%= form_for [:admin, @player] do |f| %>
  <%= render "shared/error_messages", object: @player %>

  <%= f.label :name %>
  <%= f.text_field :name, class: "form-control" %>

  <%= f.label :date_of_birth %>
  <%= f.text_field :date_of_birth, class: "form-control" %>

  <%= f.label :position %>
  <%= f.text_field :position, class: "form-control" %>

  <%= f.label :jersey_number %>
  <%= f.text_field :jersey_number, class: "form-control" %>

  <%= f.label :nationality %>
  <%= f.text_field :nationality, class: "form-control" %>

  <%= f.label :image %>
  <%= f.file_field :image, accept: "image/jpeg, image/gif, image/png" %>

  <%= f.label :team %>
  <%= f.select :team_id, @teams.collect {|team| [ team.name, team.id ]},
    {include_blank: false}, {class: "form-control"} %>

  <%= f.submit class: "btn btn-primary" %>
<% end %>

app/views/admin/players/edit.html.erb
<% provide :title, t("admin.player.player_name") %>
<div class="row">
  <div class="col-md-6">
    <h2><%= t "admin.player.player_name" %></h2>
    <%= render "form" %>
  </div>
</div>

app/views/admin/players/index.html.erb
<%= render "layouts/search" %>
<div class="row">
  <div class="col-md-10 col-offset-2">
    <h2><%= t "admin.player.list_player" %></h2>
    <p class="pull-right label label-info"><%= link_to t("admin.player.new_player"),
      new_admin_player_path %></p>
    <table class="table table-striped table-hover">
      <thead>
        <th><%= t "admin.player.name" %></th>
        <th><%= t "admin.player.date_of_birth" %></th>
        <th><%= t "admin.player.position" %></th>
        <th><%= t "admin.player.jersey_number" %></th>
        <th><%= t "admin.player.nationality" %></th>
        <th><%= t "admin.player.image" %></th>
        <th><%= t "admin.player.team" %></th>
        <th><%= t "admin.player.update" %></th>
        <th><%= t "admin.player.delete" %></th>
      </thead>
      <tbody>
        <% @players.each do |player| %>
          <tr>
            <td><%= link_to player.name, admin_player_path(player) %></td>
            <td><%= player.date_of_birth %></td>
            <td><%= player.position %></td>
            <td><%= player.jersey_number %></td>
            <td><%= player.nationality %></td>
            <td class="td_style"><%= image_tag player.image.url if player.image? %></td>
            <td><%= player.team.name %></td>
            <td><%= link_to t("admin.player.edit_player"), edit_admin_player_path(player) %></td>
            <td class="td_style"><%= link_to t("admin.player.destroy"), admin_player_path(player),
              method: :delete, data: {confirm: t("admin.player.sure")} %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/admin/players/new.html.erb
<% provide :title, t("admin.player.player_name") %>
<% provide :button_text, t("admin.player.create_player") %>
<div class="row">
  <div class="col-md-6">
    <h2><%= t "admin.player.create_player" %></h2>
      <%= render "form" %>
  </div>
</div>

app/views/admin/players/show.html.erb
<%= render "static_pages/top_header" %>
<div class="row">
  <div class="col-md-8">
    <div class="col-md-6">
      <div class="tt-player-logo">
        <%= image_tag @player.image.url if @player.image? %>  
      </div>
    </div>
    <div class="col-md-6">
      <h2><%= t "admin.player.detail_player" %></h2>
      <h4><span class="label label-success"><%= (t "admin.player.name") %></span>
        <%= @player.name %></h4>
      <h4><span class="label label-success"><%= (t "admin.player.date_of_birth") %></span>
        <%= @player.date_of_birth %></h4>
      <h4><span class="label label-success"><%= (t "admin.player.position") %></span>
        <%= @player.position %></h4>
      <h4><span class="label label-success"><%= (t "admin.player.jersey_number") %></span>
        <%= @player.jersey_number %></h4> 
      <h4><span class="label label-success"><%= (t "admin.player.nationality") %></span>
        <%= @player.nationality %></h4>
      <h4><span class="label label-success"><%= (t "admin.player.team") %></span>
        <%= @player.team.name %></h4>  
    </div>  
  </div>
  <%= render partial: "static_pages/left_content_ranking", seasons: @seasons %>
</div>
<%= render "static_pages/bottom_footer" %>