config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {omniauth_callbacks: "callbacks"}

  root "static_pages#home"
  get "static_pages/help"
  resources :users
  resources :posts, only: [:index, :show]
  resources :teams
  resources :players
  resources :comments
  resources :bets, only: [:edit, :update]
  
  resources :matches do 
    resources :bets, except: [:destroy, :show, :index]
  end

  namespace :admin do
    root "seasons#show"
    resources :seasons
    resources :matches
    resources :players
    resources :teams
    resources :posts
    resources :users
  end
end

app/models/season.rb
class Season < ActiveRecord::Base
  has_many :season_teams
  has_many :matches, dependent: :destroy
  has_many :season_teams, dependent: :destroy
  has_many :posts, dependent: :destroy
  has_many :team, through: :season_teams

  validates :name, presence: true, length: {maximum: 50}
  validates :description, presence:  true, length: {maximum: 100}

  def load_matches
    self.matches.group_by &:start_date
  end

  def load_season_team
    self.season_teams.order rank: :desc
  end
end

app/controllers/admin/seasons_controller.rb
class Admin::SeasonsController < ApplicationController
  load_and_authorize_resource

  def index
    @q = Season.search params[:q]
    @seasons = @q.result distinct: true
  end

  def new
  end

  def edit
  end

  def create
    if @season.save
      flash.now[:success] = t "admin.season.create_success"
      redirect_to admin_seasons_path
    else
      flash[:warning] = t "admin.season.wrong"
      render :new
    end
  end

  def update
    if @season.update_attributes season_params
      flash[:success] = t "admin.season.update_season_success"
      respond_to do |format|
        format.html {redirect_to admin_seasons_path}
        format.js
      end
    else
      flash[:danger] = t "admin.season.update_season_error"
      render :edit
    end
  end

  def destroy
    @season.destroy
    flash[:success] = t "admin.season.delete_season_success"
    redirect_to admin_seasons_path
  end

  private
  def season_params
    params.require(:season).permit :name, :description, :number_of_team,
      :number_of_match
  end
end

app/views/admin/seasons/_form.html.erb
<%= form_for [:admin, @season] do |f| %>
  <%= render "shared/error_messages", object: @season %>

  <%= f.label :name %>
  <%= f.text_field :name, class: "form-control" %>

  <%= f.label :description %>
  <%= f.text_field :description, class: "form-control" %>

  <%= f.submit class: "btn btn-primary" %>
<% end %>

app/views/admin/seasons/edit.html.erb
<% provide :title, t("admin.season.season_name") %>
<div class="row">
  <div class="col-md-6">
    <h2><%= t "admin.season.season_name" %></h2>
      <%= render "form" %>
  </div>
</div>

app/views/admin/seasons/index.html.erb
<%= render "layouts/search" %>
<div class="row">
  <div class="col-md-10 col-offset-2">
    <h2><%= t "admin.season.list_season" %></h2>
    <p class="pull-right label label-info"><%= link_to t("admin.season.new_season"),
      new_admin_season_path %></p>
    <table class="table table-striped table-hover">
      <thead>
        <th><%= t "admin.season.name" %></th>
        <th><%= t "admin.season.description" %></th>
        <th><%= t "admin.season.number_of_team" %></th>
        <th><%= t "admin.season.number_of_match" %></th>
        <th><%= t "admin.season.update" %></th>
        <th><%= t "admin.season.delete" %></th>
      </thead>
      <tbody>
        <% @seasons.each do |season| %>
          <tr>
            <td><%= link_to season.name, admin_season_path(season) %></td>
            <td><%= season.description %></td>
            <td><%= season.season_teams.count %></td>
            <td><%= season.matches.count %></td>
            <td><%= link_to t("admin.season.edit_season"), edit_admin_season_path(season) %></td>
            <td class="td_style"><%= link_to t("admin.season.destroy"), admin_season_path(season),
              method: :delete, data: {confirm: t("admin.season.sure")} %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/admin/seasons/new.html.erb
<% provide :title, t("admin.season.season_name") %>
<% provide :button_text, t("admin.season.create_season") %>
<div class="row">
  <div class="col-md-6">
    <h2><%= t "admin.season.create_season" %></h2>
      <%= render "form" %>
  </div>
</div>