config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {omniauth_callbacks: "callbacks"}

  root "static_pages#home"
  get "static_pages/help"
  resources :users
  resources :posts, only: [:index, :show]
  resources :teams
  resources :players
  resources :comments
  resources :bets, only: [:edit, :update]
  
  resources :matches do 
    resources :bets, except: [:destroy, :show, :index]
  end

  namespace :admin do
    root "seasons#show"
    resources :seasons
    resources :matches
    resources :players
    resources :teams
    resources :posts
    resources :users
  end
end

app/models/match.rb
class Match < ActiveRecord::Base
  has_many :bets
  has_many :team_matches, dependent: :destroy
  has_many :posts, dependent: :destroy
  has_many :teams, through: :team_matches
  validates :name, presence: true, length: {maximum: 50}
  validates :description, presence: true, length: {maximum: 255}

  accepts_nested_attributes_for :team_matches, allow_destroy: true

  belongs_to :season

  def goals
    self.team_matches.map(&:goals).join(" - ")
  end

  def points
    self.team_matches.map{|team_match| team_match.points}.join(" - ")
  end

  def exist_bet? user
    bets.select{|bet| bet.user_id == user.id}.count > 0
  end

  def load_bet user
    bets.select{|bet| bet.user_id == user.id}
  end
end

app/controllers/admin/matches_controller.rb
class Admin::MatchesController < ApplicationController
  load_and_authorize_resource
  before_action :load_seasons, except: [:index, :destroy]
  before_action :load_teams, except: [:index, :destroy]
  before_action :load_team_matches
  
  def index
    @q = Match.search params[:q]
    @matches = @q.result distinct: true
  end

  def new
    2.times do
      @match.team_matches.build
    end
  end

  def edit
  end

  def create
    if @match.save
      flash[:success] = t "admin.match.create_success"
      redirect_to admin_matches_path
    else
      render :new
    end
  end

  def update
    if @match.update_attributes match_params
      flash[:success] = t "admin.match.update_success"
      redirect_to admin_matches_path
    else
      flash[:danger] = t "admin.match.update_error"
      render :edit
    end
  end

  def destroy
    if @match.destroy
      flash[:success] = t "admin.match.delete_message"
      redirect_to admin_matches_path
    else
      flash[:danger] = t "admin.match.delete_error"
      render :index
    end
  end

  private
  def match_params
    params.require(:match).permit :name, :description, :start_date,
      :hour, :stadium, :season_id,
      team_matches_attributes: [:id, :team_id, :goals, :points]
  end

  def load_seasons
    @seasons = Season.all
  end

  def load_teams
    @teams = Team.all
  end

  def load_team_matches
    @team_matches = TeamMatch.all
  end
end

app/views/admin/matches/_form.html.erb
<% i = 0 %>
<%= form_for [:admin, @match] do |f| %>
  <%= render "shared/error_messages", object: @match %>
  <%= f.fields_for :team_matches, f.object.team_matches do |team_match_builder| %>
    <%= f.label :team_id %>

    <%= team_match_builder.select :team_id,
      options_for_select(@teams.collect {|team| [team.name, team.id]},
      selected: team_match_builder.object.team_id),
      {}, {class: "form-control", id: "team_#{i += 1}"} %>
    <div class="panel-heading border-from">
      <span class="panel-title"><%= t "admin.match.rate" %></span>
      <%= render "team_matches", f: team_match_builder %>
    </div>
  <% end %>

  <%= f.hidden_field :name %>
 
  <%= f.label :description %>
  <%= f.text_area :description, class:"form-control" %>
 
  <%= f.label :start_date %>
  <%= f.text_field :start_date, class: "form-control" %>
 
  <%= f.label :hour %>
  <%= f.text_field :hour, class: "form-control" %>

  <%= f.label :stadium %>
  <%= f.text_field :stadium, class: "form-control" %>

  <%= f.select :season_id, @seasons.collect {|season| [season.name, season.id]},
    {include_blank: false}, {class: "form-control"} %>
 
  <%= f.submit class: "btn btn-info form-button", id: "match_btn" %>
<% end %>

app/views/admin/matches/_team_matches.html.erb
<div class="input-group fields">
  <%= f.label :goals %>
  <%= f.text_field :goals, class: "form-control", placeholder: t("home.goal") %><br />

  <%= f.label :points %>
  <%= f.text_field :points, class: "form-control", placeholder: t("home.point") %>
</div>

app/views/admin/matches/edit.html.erb
<% provide :title, t("admin.match.match") %>
<div class="row mainbox col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2">
  <div class="alert alert-danger" style="display:none"></div>
  <div class="panel panel-info form-style">
    <div class="panel-heading">
      <div class="panel-title"><%= t "admin.match.match_edit" %></div>
    </div>
    <div class="panel-body" >
      <%= render "form" %>
    </div>
  </div>
</div>

app/views/admin/matches/index.html.erb
<%= render "layouts/search" %>
<div class="row">
  <div class="col-md-10 col-offset-2">
    <h2><%= t "admin.list_match" %></h2>
    <p class="pull-right label label-info"><%= link_to t("admin.new_match"),
      new_admin_match_path %></p>
    <table class="table table-striped table-hover table-style">
      <thead>
        <th class="th-style"><p><%= t "admin.match.name" %></p></th>
        <th class="th-style"><p><%= t "admin.match.description" %></p></th>
        <th class="th-style"><p><%= t "admin.match.startDate" %></p></th>
        <th class="th-style"><p><%= t "admin.match.hour" %></p></th>
        <th class="th-style"><p><%= t "admin.match.stadium" %></p></th>
        <th class="th-style"><p><%= t "admin.match.season" %></p></th>
        <th></th>
        <th></th>
      </thead>
      <tbody>
        <% @matches.each do |match| %>
          <tr>
            <td class="td_style"><%= match.name %></td>
            <td class="td_style"><%= match.description %></td>
            <td class="td_style"><%= match.start_date %></td>
            <td class="td_style"><%= match.hour %></td>
            <td class="td_style"><%= match.stadium %></td>
            <td class="td_style"><%= match.season.name %></td>
            <td class="td_style"><%= link_to t("admin.match.delete"), admin_match_path(match),
              method: :delete, data: {confirm: t("admin.match.delete_message")} %>
            </td>
            <td><%= link_to t("admin.match.edit"), edit_admin_match_path(match) %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/admin/matches/new.html.erb
<% provide :button_text, t("admin.match.create_match") %>
<% provide :title, t("admin.match.match") %>
<div class="row mainbox col-md-8 col-md-offset-2">
  <div class="alert alert-danger none"></div>
  <div class="panel panel-info form-style">
    <div class="panel-heading">
      <div class="panel-title"><%= t "admin.match.new" %></div>
    </div>
    <div class="panel-body" >
      <%= render "form" %>
    </div>
  </div>
</div>